language: node_js
node_js:
  - "10"
services:
  - docker
before_install:
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:7.1.1
  - docker run -d -p 9001:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.1.1
cache:
  directories:
    - "node_modules"
before_script:
  - sleep 10
  - "yarn run build"
