version: "2.2"
services:
  healthnewsapi:
    image: healthnewsapi/healthnewsapi
    environment:
      - NODE_ENV=production
      - URL_DB_NEWS=http://elasticsearch-healthnews-api:9200
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch-healthnews-api
    links:
      - elasticsearch-healthnews-api

  elasticsearch-healthnews-api:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch-healthnews-api
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - esdata-news:/usr/share/elasticsearch/data

volumes:
  esdata-news:

