version: "2.2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=production
      - URL_DB_NEWS=http://elasticsearch:9200
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    command: ["./run_server.sh"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data

volumes:
  esdata1:

